DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS sensor_types CASCADE;
DROP TABLE IF EXISTS sensors CASCADE;
DROP TABLE IF EXISTS sensor_readings CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;

