DROP TABLE IF EXISTS locations CASCADE;

DROP TABLE IF EXISTS sensortypes CASCADE;

DROP TABLE IF EXISTS sensors CASCADE;

DROP TABLE IF EXISTS sensorreadings CASCADE;

DROP TABLE IF EXISTS alerts CASCADE;

DROP TABLE IF EXISTS admins CASCADE;